'use strict';
const $=id=>document.getElementById(id);let current=null,poll=null;const openRows=new Set();
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
async function api(url,options){const r=await fetch(url,options);if(r.status===401){throw Error('Your access session expired. Return to Portfolio and enter your access code.');}const data=await r.json();if(!r.ok)throw Error(data.detail||'Request failed. Try again.');return data;}
function notice(message){$('notice').textContent=message;}
function fmt(x,suffix=''){return x===null||x===undefined?'—':x+suffix;}
function render(){if(!current)return;const ready=current.rows.filter(r=>r.status==='ready'), done=current.status!=='running';$('scorecard').hidden=false;$('progressWrap').hidden=done;$('progress').max=current.tickers.length;$('progress').value=current.rows.length;$('progressText').textContent=`${current.rows.length} / ${current.tickers.length} processed`;$('cardTitle').textContent=current.status==='failed'?'Ranking could not start':done?'Your ranked watchlist':'Ranking in progress';$('meta').textContent=`${current.horizon} · ${current.source} · Model v${current.version} · ${current.status==='failed'?'No scores generated':done?'Final ranking':'Provisional order'}`;$('scored').textContent=ready.length;$('average').textContent=ready.length?(ready.reduce((a,r)=>a+r.score,0)/ready.length).toFixed(1):'—';$('strong').textContent=ready.filter(r=>r.score>=8).length;$('missing').textContent=current.rows.length-ready.length;$('csv').disabled=!done||!current.rows.length;$('print').disabled=!done||!current.rows.length;
 const filter=$('filter').value.trim().toUpperCase(),body=$('rows');body.replaceChildren();let rank=0,count=0;
 for(const r of current.rows){if(r.status==='ready')rank++;if(!r.ticker.includes(filter))continue;count++;const tr=node('tr');tr.dataset.ticker=r.ticker;tr.append(node('td',r.status==='ready'?rank:'—'));const stock=node('td',r.ticker);if(r.as_of)stock.append(node('div',r.as_of,'date'));tr.append(stock);const cell=node('td');if(r.status==='ready'){cell.append(node('div',r.score.toFixed(1),'score'));const bar=node('div',undefined,'bar'),fill=node('i');fill.style.width=(r.score*10)+'%';bar.append(fill);cell.append(bar);}else cell.append(node('span','Unavailable','small muted'));tr.append(cell,node('td',r.reason));const toggleCell=node('td');if(r.status==='ready'){const toggle=node('button',openRows.has(r.ticker)?'Hide':'Details','secondary');toggle.setAttribute('aria-expanded',String(openRows.has(r.ticker)));toggle.setAttribute('aria-controls','detail-'+r.ticker);toggle.addEventListener('click',()=>{if(openRows.has(r.ticker))openRows.delete(r.ticker);else openRows.add(r.ticker);render();const button=[...body.querySelectorAll('button')].find(b=>b.getAttribute('aria-controls')==='detail-'+r.ticker);button?.focus();});toggleCell.append(toggle);}tr.append(toggleCell);body.append(tr);
 if(openRows.has(r.ticker)&&r.status==='ready'){const row=node('tr',undefined,'detail');row.id='detail-'+r.ticker;const td=node('td');td.colSpan=5;if(r.qualitative_summary)td.append(node('p',r.qualitative_summary,'qualitative-summary'));const grid=node('div',undefined,'evidence');for(const [label,value] of [['Price',fmt(r.price)],['RSI (14)',fmt(r.rsi)],['MACD histogram',fmt(r.macd_histogram)],['ATR / price',fmt(r.atr_pct,'%')],['Volume / 20-day',fmt(r.volume_ratio,'×')],['20 / 50 / 200-day MA',`${r.ma20} / ${r.ma50} / ${r.ma200}`],['21-session vs SPY',fmt(r.excess_21d,' pp')],['63-session vs SPY',fmt(r.excess_63d,' pp')],['Above 20-day MA',fmt(r.extension_pct,'%')],['Support / stop reference',`${r.support} / ${r.stop_reference}`]]){const item=node('div');item.append(node('span',label),node('b',value));grid.append(item);}td.append(grid);const components=node('div',undefined,'components');for(const [key,value] of Object.entries(r.components))components.append(node('span',`${key.replaceAll('_',' ')}: ${value.toFixed(0)} / 100`));td.append(components,node('p',`Stop-reference distance: ${r.stop_distance_pct}%. ${r.data_provider || 'Yahoo Finance'} · ${r.price_basis || 'adjusted'} prices; SPY from ${r.benchmark_provider || 'Yahoo Finance'}. Latest session can be incomplete.${r.price_basis==='unadjusted'?' Corporate actions may affect unadjusted indicators; both stock and SPY use unadjusted prices.':''}`, 'small muted'));const link=node('a','Source price history ↗');link.href=r.source;link.target='_blank';link.rel='noopener noreferrer';td.append(link);row.append(td);body.append(row);}}
 window.showRankingCharts?.(current);
 $('empty').hidden=count!==0; $('empty').textContent=current.status==='failed'?'No scores generated. Retry the ranking after market data becomes available.':current.status==='running'?'Waiting for matching results…':'No matching tickers.';
}
async function refresh(){try{current=await api('/api/ranking/'+current.id);render();if(current.status==='running')poll=setTimeout(refresh,2500);else{$('run').disabled=false;notice(current.error||`Complete: ${current.rows.filter(r=>r.status==='ready').length} stocks scored. Unavailable stocks are listed without ratings.`);}}catch(e){$('run').disabled=false;notice(e.message+' Results remain visible; retry by reloading.');}}
$('run').addEventListener('click',async()=>{clearTimeout(poll);$('run').disabled=true;notice('Preparing daily-chart analysis…');try{current=await api('/api/ranking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('tickers').value})});openRows.clear();localStorage.setItem('rmRankingJob',current.id);render();notice('Analyzing sequentially to keep the server responsive. Larger lists may take several minutes.');poll=setTimeout(refresh,1500);}catch(e){$('run').disabled=false;notice(e.message);}});
$('upload').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>2000000){notice('File limit is 2 MB.');return;}try{const result=await api('/api/ranking/parse?filename='+encodeURIComponent(file.name),{method:'POST',body:file});$('tickers').value=result.tickers.join('\n');notice(`${result.tickers.length} unique tickers imported. Ready to rank.`);}catch(e){notice(e.message);}finally{$('upload').value='';}});
$('filter').addEventListener('input',render);$('print').addEventListener('click',async()=>{if(!current)return;const button=$('print');button.disabled=true;button.textContent='Building PDF…';try{const response=await fetch(`/api/ranking/${current.id}/pdf?limit=${$('chartLimit').value}&market_adjusted=${$('removeMarket').checked}`);if(!response.ok){const error=await response.json();throw Error(error.detail||'PDF could not be generated.');}const url=URL.createObjectURL(await response.blob()),a=node('a');a.href=url;a.download='GSWM_Technical_Scorecard.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){notice(e.message);}finally{button.disabled=false;button.textContent='Download PDF';}});
$('csv').addEventListener('click',()=>{const fields=['rank','ticker','score','return_1y','status','reason','qualitative_summary','as_of','price','rsi','macd_histogram','ma20','ma50','ma200','atr_pct','extension_pct','support','stop_reference','stop_distance_pct','volume_ratio','excess_21d','excess_63d','trend','momentum','relative_strength','entry_risk','volume','source','data_provider','price_basis','benchmark_provider','model_version'];let rank=0;const lines=[fields.join(',')];for(const row of current.rows){const r={...row,...row.components,rank:row.status==='ready'?++rank:'',model_version:current.version};lines.push(fields.map(f=>{let v=String(r[f]??'');if(/^[=+@\t\r]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"';}).join(','));}const blob=new Blob([lines.join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='RM_Technical_Scorecard.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
const saved=localStorage.getItem('rmRankingJob');if(saved){current={id:saved};$('run').disabled=true;notice('Restoring your running scorecard…');refresh();}
