'use strict';
(()=>{
 const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
 const palette=['#1A4F8B','#487EA7','#286E66','#785A91','#A55767','#596773'];let data=null, selected=null, requestNumber=0,jobId=null;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const svg=(tag,attrs={},text)=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;};
 function color(p){return data.clusters[p.cluster].members.length>1?groupColor(p.cluster):'#8A98A9';}
 function groupColor(id){return palette[id]||`hsl(${Math.round(id*137.508)%360} 42% 42%)`;}
 function chart(id,title){const s=$(id);s.replaceChildren();s.setAttribute('viewBox','0 0 960 560');s.setAttribute('role','group');s.setAttribute('aria-label',title);s.append(svg('title',{},title));return s;}
 function text(s,x,y,value,attrs={}){s.append(svg('text',{x,y,fill:'#65758B','font-size':14,...attrs},value));}
 function range(values){let lo=Math.min(...values),hi=Math.max(...values);if(lo===hi){lo-=1;hi+=1;}const pad=(hi-lo)*.1;return [lo-pad,hi+pad];}
 function pointInfo(p){$('pointInsight').textContent=`${p.ticker} · Score ${p.score.toFixed(1)} / 10${p.return_1y===null?'':` · 12-month return ${p.return_1y.toFixed(1)}%`} · ${data.clusters[p.cluster].members.length>1?`Group ${p.cluster+1}: ${data.clusters[p.cluster].members.join(', ')}`:'No group meets the 0.75 threshold for this stock'}`;}
 function dot(s,p,x,y){const circle=svg('circle',{cx:x,cy:y,r:6+p.score*.55,fill:color(p),stroke:'#fff','stroke-width':2,tabindex:0,role:'button','aria-label':`${p.ticker}, score ${p.score.toFixed(1)}. Select correlation group.`,opacity:selected===null||selected===p.cluster?1:.18});circle.append(svg('title',{},`${p.ticker} · ${p.score.toFixed(1)} / 10${p.return_1y===null?'':` · 12-month return ${p.return_1y.toFixed(1)}%`}`));const activate=()=>{selected=p.cluster;draw();pointInfo(p);};circle.addEventListener('pointerenter',()=>pointInfo(p));circle.addEventListener('focus',()=>pointInfo(p));circle.addEventListener('click',activate);circle.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate();}});s.append(circle);}
 // Keep actual point coordinates fixed; move only text, with leader lines.
 function labels(s,positions){const boxes=[],visible=positions.filter((v,i)=>selected===null?(positions.length<=20||i<10):v.p.cluster===selected);
 for(const {p,x,y} of visible){const w=p.ticker.length*8+12,h=22;let box=null;
  for(let radius=18;radius<=180&&!box;radius+=18){for(const [dx,dy] of [[1,-1],[1,1],[-1,-1],[-1,1],[0,-1],[0,1],[1,0],[-1,0]]){const bx=x+dx*radius-(dx<=0?w:0),by=y+dy*radius-h/2;const candidate={x:bx,y:by,w,h};if(bx<34||bx+w>928||by<28||by+h>490)continue;if(boxes.some(b=>bx<b.x+b.w+5&&bx+w+5>b.x&&by<b.y+b.h+4&&by+h+4>b.y))continue;if(positions.some(v=>v.x>bx-10&&v.x<bx+w+10&&v.y>by-10&&v.y<by+h+10))continue;box=candidate;break;}}
  if(!box)continue;boxes.push(box);const lx=Math.max(box.x,Math.min(x,box.x+box.w)),ly=Math.max(box.y,Math.min(y,box.y+box.h));s.append(svg('line',{x1:x,y1:y,x2:lx,y2:ly,stroke:color(p),'stroke-width':1,opacity:.55,'pointer-events':'none'}));s.append(svg('rect',{x:box.x,y:box.y,width:box.w,height:box.h,rx:4,fill:'#fff',opacity:.94,'pointer-events':'none'}));text(s,box.x+6,box.y+16,p.ticker,{fill:'#14213D','font-size':13,'font-weight':600,'pointer-events':'none'});
 }
 }
 function scatter(){const s=chart('returnScatter','Trailing 12-month return versus technical score');const points=data.points.filter(p=>p.return_1y!==null&&Number.isFinite(p.return_1y));if(!points.length){text(s,50,150,'A full 253-session price history is needed for this graph.');return;}const[lo,hi]=range(points.map(p=>p.return_1y));const x=v=>90+(v-lo)/(hi-lo)*810,y=v=>475-(v-1)/9*410;
 s.append(svg('rect',{x:90,y:y(10),width:810,height:y(8)-y(10),fill:'#EAF1FA'}));text(s,900,48,'Strong setups: score 8–10',{'text-anchor':'end',fill:'#1A4F8B'});
 for(const score of [1,2,4,6,8,10]){s.append(svg('line',{x1:90,x2:900,y1:y(score),y2:y(score),stroke:'#DCE3EC'}));text(s,74,y(score)+5,score,{'text-anchor':'end'});}
 for(let i=0;i<6;i++){const v=lo+(hi-lo)*i/5;text(s,x(v),505,`${v.toFixed(0)}%`,{'text-anchor':'middle'});}
 if(lo<0&&hi>0)s.append(svg('line',{x1:x(0),x2:x(0),y1:65,y2:475,stroke:'#B9C9DC','stroke-dasharray':'5 5'}));text(s,490,545,'Trailing 12-month return (%) →',{'text-anchor':'middle','font-size':16});text(s,30,22,'Technical score / 10 ↑',{'font-size':16,fill:'#14213D'});const positions=points.map(p=>({p,x:x(p.return_1y),y:y(p.score)}));positions.forEach(v=>dot(s,v.p,v.x,v.y));labels(s,positions);
 }
 function map(){const s=chart('correlationMap','Correlation map: nearby stocks have similar daily returns');const[xlo,xhi]=range(data.points.map(p=>p.x)),[ylo,yhi]=range(data.points.map(p=>p.y));
 // Equal units on both axes preserve the projection's relative distances.
 const scale=Math.min(800/(xhi-xlo),420/(yhi-ylo)),x=v=>480+(v-(xlo+xhi)/2)*scale,y=v=>265-(v-(ylo+yhi)/2)*scale;
 s.append(svg('rect',{x:30,y:25,width:900,height:480,rx:10,fill:'#F7F9FC',stroke:'#E3EAF2'}));const positions=data.points.map(p=>({p,x:x(p.x),y:y(p.y)}));
 data.clusters.filter(c=>c.members.length>1).forEach(c=>{const members=positions.filter(v=>v.p.cluster===c.id),cx=members.reduce((a,v)=>a+v.x,0)/members.length,cy=members.reduce((a,v)=>a+v.y,0)/members.length,rx=Math.max(...members.map(v=>Math.abs(v.x-cx)))+25,ry=Math.max(...members.map(v=>Math.abs(v.y-cy)))+25;s.append(svg('ellipse',{cx,cy,rx,ry,fill:groupColor(c.id),'fill-opacity':selected===null||selected===c.id ? .07 : .02,stroke:groupColor(c.id),'stroke-opacity':.3,'stroke-dasharray':'5 5','pointer-events':'none'}));});
 positions.forEach(v=>dot(s,v.p,v.x,v.y));labels(s,positions);text(s,480,545,'Closer = more similar daily-return patterns',{'text-anchor':'middle','font-size':16});
 $('mapNote').textContent=`This map compresses many relationships into 2D (${(data.map_variance_explained*100).toFixed(0)}% of positive embedding variance shown). Axes have no return or score units. Colored outlines identify qualifying groups; verify exact pairs below.`;
 }
 function cellColor(r){if(r>=0){const amount=r;return `rgb(${Math.round(240-214*amount)},${Math.round(245-166*amount)},${Math.round(250-111*amount)})`;}const a=-r;return `rgb(${Math.round(240-66*a)},${Math.round(245-161*a)},${Math.round(250-147*a)})`;}
 function matrix(){const s=$('correlationHeatmap');s.replaceChildren();const n=data.tickers.length,size=n>25?30:40,offset=108,width=offset+n*size+16;s.setAttribute('viewBox',`0 0 ${width} ${width}`);s.style.minWidth=`${Math.max(650,width)}px`;s.setAttribute('role','group');s.setAttribute('aria-label','Pairwise daily-return correlation heatmap');s.append(svg('title',{},'Pairwise return correlation. Diagonal is 1.00.'));
 for(let i=0;i<n;i++){text(s,offset-8,offset+i*size+size*.68,data.tickers[i],{'text-anchor':'end','font-size':13});text(s,offset+i*size+size*.6,offset-10,data.tickers[i],{transform:`rotate(-55 ${offset+i*size+size*.6} ${offset-10})`,'font-size':13});for(let j=0;j<n;j++){const r=data.matrix[i][j],p=data.points[i];const c=svg('rect',{x:offset+j*size,y:offset+i*size,width:size-1,height:size-1,fill:cellColor(r),opacity:selected===null||(p.cluster===selected&&data.points[j].cluster===selected)?1:.25,tabindex:i<j?0:-1,role:'button','aria-label':`${data.tickers[i]} and ${data.tickers[j]}: correlation ${r.toFixed(2)}`});c.append(svg('title',{},`${data.tickers[i]} / ${data.tickers[j]} · ${r.toFixed(3)}`));const show=()=>{$('clusterInfo').textContent=`${data.tickers[i]} + ${data.tickers[j]}: ${r.toFixed(3)} correlation across ${data.sample_count} daily returns${data.market_adjusted?', after removing SPY exposure':''}.`;};c.addEventListener('click',show);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show();}});s.append(c);if(n<=50)text(s,offset+j*size+size/2,offset+i*size+size*.68,r.toFixed(2),{'text-anchor':'middle','font-size':11,fill:Math.abs(r)>.55?'white':'#3E4759','pointer-events':'none'});}}
 }
 function groups(){const legend=$('clusterLegend');legend.replaceChildren();data.clusters.filter(c=>c.members.length>1).forEach(c=>{const b=el('button', `Group ${c.id+1}: ${c.members.length} stocks · avg ${c.average_correlation.toFixed(2)}`,'cluster-chip');b.style.borderLeftColor=groupColor(c.id);b.setAttribute('aria-pressed',String(selected===c.id));b.addEventListener('click',()=>{selected=c.id;draw();});legend.append(b);});legend.append(el('span','Gray = no qualifying group','legend-neutral'));if(!data.clusters.some(c=>c.members.length>1))legend.append(el('span','No group meets the 0.75 correlation threshold.','muted small'));
 if(selected!==null){const c=data.clusters[selected];$('clusterInfo').textContent=`${c.members.join(', ')}${c.members.length>1?` · Average correlation ${c.average_correlation.toFixed(3)} · Lowest pair ${c.minimum_correlation.toFixed(3)}`:' · No qualifying correlated group'}.`; }else{const largest=data.clusters.filter(c=>c.members.length>1).sort((a,b)=>b.members.length-a.members.length)[0];$('clusterInfo').textContent=largest?`Largest qualifying group: ${largest.members.join(', ')} · All member pairs ≥0.75. Select a group to highlight it across the charts and scorecard.`:'No group has every pair ≥0.75. Select a stock or heatmap cell to explore individual relationships.';}
 $('clearCluster').hidden=selected===null;document.querySelectorAll('#rows > tr[data-ticker]').forEach(r=>{const p=data.points.find(p=>p.ticker===r.dataset.ticker);r.classList.toggle('cluster-selected',selected!==null&&p?.cluster===selected);});
 }
 function draw(){if(!data?.available)return;$('pointInsight').textContent='Hover, focus, or select a stock to see its ticker, score, return, and group.';scatter();map();matrix();groups();}
 async function load(){if(!jobId)return;const thisRequest=++requestNumber;$('chartStatus').textContent='Comparing daily returns…';$('chartContent').hidden=true;try{const response=await fetch(`/api/ranking/${jobId}/analytics?limit=${$('chartLimit').value}&market_adjusted=${$('removeMarket').checked}`);const result=await response.json();if(thisRequest!==requestNumber)return;if(!response.ok)throw Error(result.detail||'Comparison unavailable.');data=result;selected=null;if(!data.available){$('chartStatus').textContent=data.reason;return;}$('chartContent').hidden=false;$('chartStatus').textContent=`${data.tickers.length} stocks · ${data.sample_count} overlapping daily returns · ${data.start} to ${data.end} · ${data.market_adjusted?'SPY effect removed':'Overall return correlation'} · ${data.price_basis} prices${data.excluded.length?` · Excluded: ${data.excluded.join(', ')} (incompatible basis or insufficient variation)`:''}`;draw();}catch(e){if(thisRequest===requestNumber)$('chartStatus').textContent=e.message;}}
 $('chartLimit').addEventListener('change',load);$('removeMarket').addEventListener('change',load);$('clearCluster').addEventListener('click',()=>{selected=null;draw();});
 window.showRankingCharts=job=>{if(job?.status!=='complete'){$('correlationSection').hidden=true;jobId=null;requestNumber++;return;}$('correlationSection').hidden=false;if(jobId!==job.id){jobId=job.id;load();}else if(data?.available)groups();};
})();
