'use strict';
(()=>{
 const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
 const palette=['#1A4F8B','#487EA7','#286E66','#785A91','#A55767','#596773'];let data=null, selected=null, requestNumber=0,jobId=null;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const svg=(tag,attrs={},text)=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;};
 function color(p){return data.clusters[p.cluster].members.length>1?groupColor(p.cluster):'#8A98A9';}
 function groupColor(id){return palette[id]||`hsl(${Math.round(id*137.508)%360} 42% 42%)`;}
 function chart(id,title){const s=$(id);s.replaceChildren();s.setAttribute('viewBox','0 0 960 560');s.setAttribute('role','group');s.setAttribute('aria-label',title);s.append(svg('title',{},title));return s;}
 function text(s,x,y,value,attrs={}){s.append(svg('text',{x,y,fill:'#65758B','font-size':14,...attrs},value));}
 function range(values){let lo=Math.min(...values),hi=Math.max(...values);if(lo===hi){lo-=1;hi+=1;}const pad=(hi-lo)*.1;return [lo-pad,hi+pad];}
 function niceScale(values){const[lo,hi]=range(values),raw=(hi-lo)/6,power=10**Math.floor(Math.log10(raw)),unit=raw/power,step=(unit<1.5?1:unit<3?2:unit<7?5:10)*power,min=Math.floor(lo/step)*step,max=Math.ceil(hi/step)*step,ticks=[];for(let v=min;v<=max+step/2;v+=step)ticks.push(Math.abs(v)<step/100?0:v);return {min,max,ticks,format:v=>`${v.toFixed(step<1?Math.ceil(-Math.log10(step)):0)}%`};}
 function pointInfo(p){$('pointInsight').textContent=`${p.ticker} · Score ${p.score.toFixed(1)} / 10${p.return_1y===null?'':` · 12-month return ${p.return_1y.toFixed(1)}%`}${Number.isFinite(p.pairCorrelation)?` · Correlation to ${$('referenceStock').value}: ${p.pairCorrelation.toFixed(3)}`:''}${Number.isFinite(p.return_100d)?` · 100-day ${p.return_100d.toFixed(1)}%`:''}${Number.isFinite(p.return_200d)?` · 200-day ${p.return_200d.toFixed(1)}%`:''} · ${data.clusters[p.cluster].members.length>1?`Group ${p.cluster+1}: ${data.clusters[p.cluster].members.join(', ')}`:'No group meets the 0.75 threshold for this stock'}`;document.querySelectorAll('.chart-insight').forEach(n=>n.textContent=$('pointInsight').textContent);}
 function dot(s,p,x,y){const circle=svg('circle',{cx:x,cy:y,r:6+p.score*.55,fill:color(p),stroke:'#fff','stroke-width':2,tabindex:0,role:'button','aria-label':`${p.ticker}, score ${p.score.toFixed(1)}. Select correlation group.`,opacity:selected===null||selected===p.cluster?1:.18});circle.append(svg('title',{},`${Number.isFinite(p.pairCorrelation)?`Correlation to ${$('referenceStock').value}: ${p.pairCorrelation.toFixed(3)} · `:''}${p.ticker} · ${p.score.toFixed(1)} / 10${p.return_1y===null?'':` · 12-month return ${p.return_1y.toFixed(1)}%`}`));const activate=()=>{selected=p.cluster;draw();pointInfo(p);};circle.addEventListener('pointerenter',()=>pointInfo(p));circle.addEventListener('focus',()=>pointInfo(p));circle.addEventListener('click',activate);circle.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate();}});s.append(circle);}
 // Keep actual point coordinates fixed; move only text, with leader lines.
 function labels(s,positions){const boxes=[],visible=positions.filter((v,i)=>selected===null?(positions.length<=20||i<10):v.p.cluster===selected);
 for(const {p,x,y} of visible){const w=p.ticker.length*8+12,h=22;let box=null;
  for(let radius=18;radius<=180&&!box;radius+=18){for(const [dx,dy] of [[1,-1],[1,1],[-1,-1],[-1,1],[0,-1],[0,1],[1,0],[-1,0]]){const bx=x+dx*radius-(dx<=0?w:0),by=y+dy*radius-h/2;const candidate={x:bx,y:by,w,h};if(bx<34||bx+w>928||by<28||by+h>490)continue;if(boxes.some(b=>bx<b.x+b.w+5&&bx+w+5>b.x&&by<b.y+b.h+4&&by+h+4>b.y))continue;if(positions.some(v=>v.x>bx-10&&v.x<bx+w+10&&v.y>by-10&&v.y<by+h+10))continue;box=candidate;break;}}
  if(!box)continue;boxes.push(box);const lx=Math.max(box.x,Math.min(x,box.x+box.w)),ly=Math.max(box.y,Math.min(y,box.y+box.h));s.append(svg('line',{x1:x,y1:y,x2:lx,y2:ly,stroke:color(p),'stroke-width':1,opacity:.55,'pointer-events':'none'}));s.append(svg('rect',{x:box.x,y:box.y,width:box.w,height:box.h,rx:4,fill:'#fff',opacity:.94,'pointer-events':'none'}));text(s,box.x+6,box.y+16,p.ticker,{fill:'#14213D','font-size':13,'font-weight':600,'pointer-events':'none'});
 }
 }
 function scatter(){const s=chart('returnScatter','Trailing 12-month return versus technical score');const points=data.points.filter(p=>p.return_1y!==null&&Number.isFinite(p.return_1y));if(!points.length){text(s,50,150,'A full 253-session price history is needed for this graph.');$('returnFinding').textContent='No stock in this comparison has a full 12-month history.';return;}const axis=niceScale(points.map(p=>p.return_1y)),lo=axis.min,hi=axis.max;const x=v=>90+(v-lo)/(hi-lo)*810,y=v=>475-(v-1)/9*410;
 s.append(svg('rect',{x:90,y:y(10),width:810,height:y(8)-y(10),fill:'#EAF1FA'}));text(s,900,48,'Strong setups: score 8–10',{'text-anchor':'end',fill:'#1A4F8B'});
 for(const score of [1,2,3,4,5,6,7,8,9,10]){s.append(svg('line',{x1:90,x2:900,y1:y(score),y2:y(score),stroke:'#DCE3EC'}));text(s,74,y(score)+5,score,{'text-anchor':'end'});}
 for(const v of axis.ticks)text(s,x(v),505,axis.format(v),{'text-anchor':'middle'});
 if(lo<0&&hi>0)s.append(svg('line',{x1:x(0),x2:x(0),y1:65,y2:475,stroke:'#B9C9DC','stroke-dasharray':'5 5'}));text(s,490,545,'Trailing 12-month return (%) →',{'text-anchor':'middle','font-size':16});text(s,30,22,'Technical score / 10 ↑',{'font-size':16,fill:'#14213D'});const positions=points.map(p=>({p,x:x(p.return_1y),y:y(p.score)}));positions.forEach(v=>dot(s,v.p,v.x,v.y));labels(s,positions);$('returnFinding').textContent=`${points.filter(p=>p.score>=8).length} of ${points.length} plotted stocks score at least 8. ${points.filter(p=>p.return_1y>0).length} gained over the last 252 sessions. This compares current setups with past performance; it does not forecast returns.`;
 }
 function horizonScatter(){const prior=$('horizonMode').value==='prior100d',key=prior?'return_prior100d':'return_200d',yLabel=prior?'Preceding 100-trading-day return':'200-trading-day return';const s=chart('horizonScatter',`100-trading-day return versus ${yLabel}`),points=data.points.filter(p=>Number.isFinite(p.return_100d)&&Number.isFinite(p[key]));$('horizonGuide').textContent=prior?'X: the most recent 100 trading days. Y: the 100 trading days immediately before that. These periods do not overlap. Upper-right stocks gained in both periods.':'X: the most recent 100 trading days. Y: the full trailing 200 trading days. These windows overlap; similar performance is not proof of daily co-movement.';
 if(!points.length){text(s,50,150,'Run a fresh ranking to calculate these return windows.');$('horizonFinding').textContent='No usable window data in this ranking.';return;}
 const xa=niceScale(points.map(p=>p.return_100d)),ya=niceScale(points.map(p=>p[key])),x=v=>90+(v-xa.min)/(xa.max-xa.min)*810,y=v=>475-(v-ya.min)/(ya.max-ya.min)*410;
 for(const v of ya.ticks){s.append(svg('line',{x1:90,x2:900,y1:y(v),y2:y(v),stroke:'#DCE3EC'}));text(s,74,y(v)+5,ya.format(v),{'text-anchor':'end'});}for(const v of xa.ticks)text(s,x(v),505,xa.format(v),{'text-anchor':'middle'});
 if(xa.min<0&&xa.max>0)s.append(svg('line',{x1:x(0),x2:x(0),y1:65,y2:475,stroke:'#9DAFC3','stroke-dasharray':'5 5'}));if(ya.min<0&&ya.max>0)s.append(svg('line',{x1:90,x2:900,y1:y(0),y2:y(0),stroke:'#9DAFC3','stroke-dasharray':'5 5'}));
 text(s,490,545,'Recent 100-trading-day return (%) →',{'text-anchor':'middle','font-size':16});text(s,30,22,yLabel+' (%) ↑',{'font-size':16,fill:'#14213D'});const positions=points.map(p=>({p,x:x(p.return_100d),y:y(p[key])}));positions.forEach(v=>dot(s,v.p,v.x,v.y));labels(s,positions);
 $('horizonFinding').textContent=prior?`${points.filter(p=>p.return_100d>0&&p[key]>0).length} stocks gained in both periods; ${points.filter(p=>p.return_100d>0&&p[key]<0).length} gained recently after a loss in the preceding period. These are historical patterns, not validated signals.`:`${points.length} stocks shown over the same ending date. The 200-day return includes the last 100 days; use the preceding-100-day option to separate the periods.`;
 }
 function peerScatter(){const reference=$('referenceStock').value,index=data.tickers.indexOf(reference);if(index<0)return;const s=chart('peerScatter',`Technical score versus daily-return correlation to ${reference}`),points=data.points.filter(p=>p.ticker!==reference).map(p=>({...p,pairCorrelation:data.matrix[index][data.tickers.indexOf(p.ticker)]})),x=v=>90+(v+1)/2*810,y=v=>475-(v-1)/9*410;
 s.append(svg('rect',{x:x(.75),y:y(10),width:x(1)-x(.75),height:y(8)-y(10),fill:'#EAF1FA'}));for(let v=1;v<=10;v++){s.append(svg('line',{x1:90,x2:900,y1:y(v),y2:y(v),stroke:'#DCE3EC'}));text(s,74,y(v)+5,v,{'text-anchor':'end'});}for(const v of [-1,-.75,-.5,-.25,0,.25,.5,.75,1])text(s,x(v),505,v.toFixed(2),{'text-anchor':'middle'});s.append(svg('line',{x1:x(.75),x2:x(.75),y1:65,y2:475,stroke:'#1A4F8B','stroke-dasharray':'5 5'}));text(s,490,545,`Daily-return correlation to ${reference} →`,{'text-anchor':'middle','font-size':16});text(s,30,22,'Technical score / 10 ↑',{'font-size':16});const positions=points.map(p=>({p,x:x(p.pairCorrelation),y:y(p.score)}));positions.forEach(v=>dot(s,v.p,v.x,v.y));labels(s,positions);
 const high=points.filter(p=>p.score>=8&&p.pairCorrelation>=.75);$('peerFinding').textContent=`${high.length} stocks meet score ≥8 and correlation ≥0.75 to ${reference}${high.length?`: ${high.map(p=>p.ticker).join(', ')}`:''}. ${data.market_adjusted?'Correlations use returns after removing each stock’s estimated SPY exposure.':'Correlations use overall daily returns.'} Strong links to one stock do not establish an all-pairs group.`;
 const list=$('peerPairs');list.replaceChildren();list.append(el('h4',`Closest daily-return relationships to ${reference}`));const table=el('table'),head=el('tr');['Stock','Correlation','Score'].forEach(v=>head.append(el('th',v)));const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');points.sort((a,b)=>b.pairCorrelation-a.pairCorrelation||a.ticker.localeCompare(b.ticker)).slice(0,5).forEach(p=>{const row=el('tr');[p.ticker,p.pairCorrelation.toFixed(3),p.score.toFixed(1)].forEach(v=>row.append(el('td',v)));body.append(row);});table.append(body);list.append(table);
 }
 function groups(){const legend=$('clusterLegend');legend.replaceChildren();data.clusters.filter(c=>c.members.length>1).forEach(c=>{const b=el('button', `Group ${c.id+1}: ${c.members.length} stocks · avg ${c.average_correlation.toFixed(2)}`,'cluster-chip');b.style.borderLeftColor=groupColor(c.id);b.setAttribute('aria-pressed',String(selected===c.id));b.addEventListener('click',()=>{selected=c.id;draw();});legend.append(b);});legend.append(el('span','Gray = no qualifying group','legend-neutral'));if(!data.clusters.some(c=>c.members.length>1))legend.append(el('span','No group meets the 0.75 correlation threshold.','muted small'));
 if(selected!==null){const c=data.clusters[selected];$('clusterInfo').textContent=`${c.members.join(', ')}${c.members.length>1?` · Average correlation ${c.average_correlation.toFixed(3)} · Lowest pair ${c.minimum_correlation.toFixed(3)}`:' · No qualifying correlated group'}.`; }else{const largest=data.clusters.filter(c=>c.members.length>1).sort((a,b)=>b.members.length-a.members.length)[0];$('clusterInfo').textContent=largest?`Largest qualifying group: ${largest.members.join(', ')} · All member pairs ≥0.75. Select a group to highlight it across the charts and scorecard.`:'No group has every pair ≥0.75. Select a stock to explore its daily-return group.';}
 $('clearCluster').hidden=selected===null;document.querySelectorAll('#rows > tr[data-ticker]').forEach(r=>{const p=data.points.find(p=>p.ticker===r.dataset.ticker);r.classList.toggle('cluster-selected',selected!==null&&p?.cluster===selected);});
 }
 function draw(){if(!data?.available)return;$('pointInsight').textContent='Hover, focus, or select a stock to see its ticker, score, return, and group.';document.querySelectorAll('.chart-insight').forEach(n=>n.textContent=$('pointInsight').textContent);scatter();horizonScatter();peerScatter();groups();}
 async function load(){if(!jobId)return;const thisRequest=++requestNumber;$('chartStatus').textContent='Comparing daily returns…';$('chartContent').hidden=true;try{const response=await fetch(`/api/ranking/${jobId}/analytics?limit=${$('chartLimit').value}&market_adjusted=${$('removeMarket').checked}`);const result=await response.json();if(thisRequest!==requestNumber)return;if(!response.ok)throw Error(result.detail||'Comparison unavailable.');data=result;selected=null;if(!data.available){$('chartStatus').textContent=data.reason;return;}const reference=$('referenceStock'),previous=reference.value;reference.replaceChildren(...data.tickers.map(t=>{const o=el('option',t);o.value=t;return o;}));reference.value=data.tickers.includes(previous)?previous:data.tickers[0];$('chartContent').hidden=false;$('chartStatus').textContent=`${data.tickers.length} stocks · ${data.sample_count} overlapping daily returns · ${data.start} to ${data.end} · ${data.market_adjusted?'SPY effect removed':'Overall return correlation'} · ${data.price_basis} prices${data.excluded.length?` · Excluded: ${data.excluded.join(', ')} (incompatible basis or insufficient variation)`:''}`;draw();}catch(e){if(thisRequest===requestNumber)$('chartStatus').textContent=e.message;}}
 $('referenceStock').addEventListener('change',()=>{selected=null;draw();});$('horizonMode').addEventListener('change',draw);
 $('chartLimit').addEventListener('change',load);$('removeMarket').addEventListener('change',load);$('clearCluster').addEventListener('click',()=>{selected=null;draw();});
 window.showRankingCharts=job=>{if(job?.status!=='complete'){$('correlationSection').hidden=true;jobId=null;requestNumber++;return;}if(jobId!==job.id){jobId=job.id;load();}else if(data?.available)groups();};
})();
